[outputsettings]                      # 横屏
fps = 60
resolution_w = 1920
resolution_h = 1080
resolution_width_preview = 360
resolution_height_preview = 240

[Gam]
speedx = 4                              # 不讲话部分几倍速
pre_time = 3                            # 讲话之前留出多少时间
aft_time = 1                            # 讲话之后留出多少时间
bet_time = 5.01                         # 两段话中间间隔多少时间
noise_sig_length = 0.2                  # 小于多少秒的信号视为噪声
growth_or_decay_time_of_voice = 0.5     # 讲话声音的衰减、增长时间，避免我采取的阈值导致声音突然出现和中断
threads = 7                             # 剪辑时用多少线程
cri_dB = 40                             # 多少分贝数视作有效人声？


[supportedFormat]
video = [".mp4", ".MP4"]
picture = [".jpg", ".png", "jpeg", ".JPG", ".PNG", "JPEG", ".GIF", ".gif"]

